######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 27 17:44:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . build
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += dbus
